site_name: FlyHostel
site_url: https://flyhosteldocs.readthedocs.io/en/latest/
repo_url: https://github.com/shaliulab/FlyHostel4
nav:
    - Home: index.md
    - Camera: camera.md
    - Idtrackerai: idtrackerai.md
    - About: about.md
theme: readthedocs

