site_name: FlyHostel
site_url: https://flyhosteldocs.readthedocs.io/en/latest/
repo_url: https://github.com/shaliulab/FlyHostel4
nav:
    - Home: index.md
    - Protocol: protocol.md
    - Camera: camera.md
    - Sensor: sensor.md
    - Incubator: incubator.md
    - Idtrackerai: idtrackerai.md
    - Backup: backup.md
    - Quantification: quantification.md
    - About: about.md
theme: readthedocs

